# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: durisosa <durisosa@student.42madrid.com    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/05/26 13:30:23 by durisosa          #+#    #+#              #
#    Updated: 2026/06/23 13:53:41 by durisosa         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC = gcc
AR = ar rcs
FLAGS = -Wall -Werror -Wextra
NAME = libft.a
RM = rm -rf
INCLUDE = -I.

CFILES = ft_atoi.c \
ft_bzero.c \
ft_calloc.c \
ft_isalpha.c \
ft_isdigit.c \
ft_isalnum.c \
ft_isascii.c \
ft_isprint.c \
ft_strlen.c \
ft_strlcat.c \
ft_strlcpy.c \
ft_strncmp.c \
ft_strnstr.c \
ft_strrchr.c \
ft_memset.c \
ft_memcpy.c \
ft_memmove.c \
ft_toupper.c \
ft_tolower.c \
ft_memchr.c \
ft_memcmp.c \
ft_strdup.c \
ft_substr.c \
ft_strjoin.c \
ft_strtrim.c \
ft_strchr.c \
ft_strrchr.c \
ft_strstr.c \
ft_split.c \
ft_itoa.c \
ft_strmapi.c \
ft_striteri.c \
ft_putchar_fd.c \
ft_putstr_fd.c \
ft_putendl_fd.c \
ft_putnbr_fd.c \
ft_lstnew.c \
ft_lstadd_front.c \
ft_lstadd_back.c \
ft_lstdelone.c \
ft_lstclear.c \
ft_lstsize.c \
ft_lstlast.c \
ft_lstiter.c \
ft_lstmap.c \
printf/ft_flags_utils.c \
printf/ft_flags.c printf/ft_printf.c \
printf/ft_printc.c printf/ft_printf_utils.c \
printf/ft_printf_xtoa.c printf/ft_printhex.c \
printf/ft_printint.c printf/ft_printptr.c \
printf/ft_printstr.c printf/ft_printuint.c

OBJS = $(CFILES:.c=.o)

$(NAME): $(OBJS)
	$(AR) ${NAME} $^

%.o: %.c
	@echo "Creating object files";
	$(CC) $(FLAGS) $(INCLUDE) -c $< -o $@

all: $(NAME)

clean:
	$(RM) $(OBJS)

fclean: clean
	$(RM) $(NAME)

re: fclean all

.PHONY: all bonus clean fclean re
